/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables;


import com.kairlec.koj.dao.Keys;
import com.kairlec.koj.dao.Koj;
import com.kairlec.koj.dao.tables.records.SubmitExtendRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 任务拓展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmitExtend extends TableImpl<SubmitExtendRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>koj.submit_extend</code>
     */
    public static final SubmitExtend SUBMIT_EXTEND = new SubmitExtend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubmitExtendRecord> getRecordType() {
        return SubmitExtendRecord.class;
    }

    /**
     * The column <code>koj.submit_extend.id</code>. 任务id
     */
    public final TableField<SubmitExtendRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "任务id");

    /**
     * The column <code>koj.submit_extend.code</code>. 代码
     */
    public final TableField<SubmitExtendRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "代码");

    /**
     * The column <code>koj.submit_extend.stdout</code>. 标准输出
     */
    public final TableField<SubmitExtendRecord, String> STDOUT = createField(DSL.name("stdout"), SQLDataType.CLOB.nullable(false), this, "标准输出");

    /**
     * The column <code>koj.submit_extend.stderr</code>. 标准错误
     */
    public final TableField<SubmitExtendRecord, String> STDERR = createField(DSL.name("stderr"), SQLDataType.CLOB.nullable(false), this, "标准错误");

    /**
     * The column <code>koj.submit_extend.create_time</code>. 创建时间
     */
    public final TableField<SubmitExtendRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>koj.submit_extend.update_time</code>. 更新时间
     */
    public final TableField<SubmitExtendRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "更新时间");

    private SubmitExtend(Name alias, Table<SubmitExtendRecord> aliased) {
        this(alias, aliased, null);
    }

    private SubmitExtend(Name alias, Table<SubmitExtendRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("任务拓展信息表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>koj.submit_extend</code> table reference
     */
    public SubmitExtend(String alias) {
        this(DSL.name(alias), SUBMIT_EXTEND);
    }

    /**
     * Create an aliased <code>koj.submit_extend</code> table reference
     */
    public SubmitExtend(Name alias) {
        this(alias, SUBMIT_EXTEND);
    }

    /**
     * Create a <code>koj.submit_extend</code> table reference
     */
    public SubmitExtend() {
        this(DSL.name("submit_extend"), null);
    }

    public <O extends Record> SubmitExtend(Table<O> child, ForeignKey<O, SubmitExtendRecord> key) {
        super(child, key, SUBMIT_EXTEND);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Koj.KOJ;
    }

    @Override
    public UniqueKey<SubmitExtendRecord> getPrimaryKey() {
        return Keys.KEY_SUBMIT_EXTEND_PRIMARY;
    }

    @Override
    public List<ForeignKey<SubmitExtendRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SUBMIT_EXTEND_IBFK_1);
    }

    private transient Submit _submit;

    /**
     * Get the implicit join path to the <code>koj.submit</code> table.
     */
    public Submit submit() {
        if (_submit == null)
            _submit = new Submit(this, Keys.SUBMIT_EXTEND_IBFK_1);

        return _submit;
    }

    @Override
    public SubmitExtend as(String alias) {
        return new SubmitExtend(DSL.name(alias), this);
    }

    @Override
    public SubmitExtend as(Name alias) {
        return new SubmitExtend(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SubmitExtend rename(String name) {
        return new SubmitExtend(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SubmitExtend rename(Name name) {
        return new SubmitExtend(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
