/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.Competition;
import com.kairlec.koj.dao.tables.Contestants;
import com.kairlec.koj.dao.tables.Problem;
import com.kairlec.koj.dao.tables.ProblemConfig;
import com.kairlec.koj.dao.tables.ProblemTag;
import com.kairlec.koj.dao.tables.TagBelongProblem;
import com.kairlec.koj.dao.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in koj.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTESTANTS_COMPETITION_ID_IDX = Internal.createIndex(DSL.name("competition_id_idx"), Contestants.CONTESTANTS, new OrderField[] { Contestants.CONTESTANTS.COMPETITION_ID }, false);
    public static final Index USER_EMAIL_IDX = Internal.createIndex(DSL.name("email_idx"), User.USER, new OrderField[] { User.USER.EMAIL }, false);
    public static final Index PROBLEM_CONFIG_LANGUAGE_ID_IDX = Internal.createIndex(DSL.name("language_id_idx"), ProblemConfig.PROBLEM_CONFIG, new OrderField[] { ProblemConfig.PROBLEM_CONFIG.LANGUAGE_ID }, false);
    public static final Index COMPETITION_NAME_IDX = Internal.createIndex(DSL.name("name_idx"), Competition.COMPETITION, new OrderField[] { Competition.COMPETITION.NAME }, false);
    public static final Index PROBLEM_NAME_IDX = Internal.createIndex(DSL.name("name_idx"), Problem.PROBLEM, new OrderField[] { Problem.PROBLEM.NAME }, false);
    public static final Index PROBLEM_TAG_NAME_IDX = Internal.createIndex(DSL.name("name_idx"), ProblemTag.PROBLEM_TAG, new OrderField[] { ProblemTag.PROBLEM_TAG.NAME }, false);
    public static final Index PROBLEM_CONFIG_PROBLEM_ID_IDX = Internal.createIndex(DSL.name("problem_id_idx"), ProblemConfig.PROBLEM_CONFIG, new OrderField[] { ProblemConfig.PROBLEM_CONFIG.PROBLEM_ID }, false);
    public static final Index TAG_BELONG_PROBLEM_PROBLEM_ID_IDX = Internal.createIndex(DSL.name("problem_id_idx"), TagBelongProblem.TAG_BELONG_PROBLEM, new OrderField[] { TagBelongProblem.TAG_BELONG_PROBLEM.PROBLEM_ID }, false);
    public static final Index TAG_BELONG_PROBLEM_TAG_ID_IDX = Internal.createIndex(DSL.name("tag_id_idx"), TagBelongProblem.TAG_BELONG_PROBLEM, new OrderField[] { TagBelongProblem.TAG_BELONG_PROBLEM.TAG_ID }, false);
    public static final Index CONTESTANTS_USER_ID_IDX = Internal.createIndex(DSL.name("user_id_idx"), Contestants.CONTESTANTS, new OrderField[] { Contestants.CONTESTANTS.USER_ID }, false);
    public static final Index USER_USERNAME_IDX = Internal.createIndex(DSL.name("username_idx"), User.USER, new OrderField[] { User.USER.USERNAME }, false);
}
