/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.UidWorkerNode;
import com.kairlec.koj.dao.tables.records.UidWorkerNodeRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * koj.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UidWorkerNodeRecord> KEY_UID_WORKER_NODE_PRIMARY = Internal.createUniqueKey(UidWorkerNode.UID_WORKER_NODE, DSL.name("KEY_uid_worker_node_PRIMARY"), new TableField[] { UidWorkerNode.UID_WORKER_NODE.ID }, true);
}
