/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.Code;
import com.kairlec.koj.dao.tables.Competition;
import com.kairlec.koj.dao.tables.Contestants;
import com.kairlec.koj.dao.tables.Problem;
import com.kairlec.koj.dao.tables.ProblemBelongCompetition;
import com.kairlec.koj.dao.tables.ProblemConfig;
import com.kairlec.koj.dao.tables.ProblemRun;
import com.kairlec.koj.dao.tables.ProblemTag;
import com.kairlec.koj.dao.tables.Submit;
import com.kairlec.koj.dao.tables.TagBelongProblem;
import com.kairlec.koj.dao.tables.UidWorkerNode;
import com.kairlec.koj.dao.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Koj extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>koj</code>
     */
    public static final Koj KOJ = new Koj();

    /**
     * 代码表
     */
    public final Code CODE = Code.CODE;

    /**
     * 比赛表
     */
    public final Competition COMPETITION = Competition.COMPETITION;

    /**
     * 参赛者关系表
     */
    public final Contestants CONTESTANTS = Contestants.CONTESTANTS;

    /**
     * 题目表
     */
    public final Problem PROBLEM = Problem.PROBLEM;

    /**
     * 题目和比赛关系表
     */
    public final ProblemBelongCompetition PROBLEM_BELONG_COMPETITION = ProblemBelongCompetition.PROBLEM_BELONG_COMPETITION;

    /**
     * 题目语言配置表
     */
    public final ProblemConfig PROBLEM_CONFIG = ProblemConfig.PROBLEM_CONFIG;

    /**
     * 题目运行内容表(非spj)
     */
    public final ProblemRun PROBLEM_RUN = ProblemRun.PROBLEM_RUN;

    /**
     * 题目标签表
     */
    public final ProblemTag PROBLEM_TAG = ProblemTag.PROBLEM_TAG;

    /**
     * 任务表
     */
    public final Submit SUBMIT = Submit.SUBMIT;

    /**
     * 题目标签关系表
     */
    public final TagBelongProblem TAG_BELONG_PROBLEM = TagBelongProblem.TAG_BELONG_PROBLEM;

    /**
     * DB WorkerID Assigner for UID Generator
     */
    public final UidWorkerNode UID_WORKER_NODE = UidWorkerNode.UID_WORKER_NODE;

    /**
     * 用户表
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Koj() {
        super("koj", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Code.CODE,
            Competition.COMPETITION,
            Contestants.CONTESTANTS,
            Problem.PROBLEM,
            ProblemBelongCompetition.PROBLEM_BELONG_COMPETITION,
            ProblemConfig.PROBLEM_CONFIG,
            ProblemRun.PROBLEM_RUN,
            ProblemTag.PROBLEM_TAG,
            Submit.SUBMIT,
            TagBelongProblem.TAG_BELONG_PROBLEM,
            UidWorkerNode.UID_WORKER_NODE,
            User.USER
        );
    }
}
