/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.UidWorkerNode;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Koj extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>koj</code>
     */
    public static final Koj KOJ = new Koj();

    /**
     * DB WorkerID Assigner for UID Generator
     */
    public final UidWorkerNode UID_WORKER_NODE = UidWorkerNode.UID_WORKER_NODE;

    /**
     * No further instances allowed
     */
    private Koj() {
        super("koj", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            UidWorkerNode.UID_WORKER_NODE);
    }
}
