/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.UidWorkerNode;


/**
 * Convenience access to all tables in koj.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * DB WorkerID Assigner for UID Generator
     */
    public static final UidWorkerNode UID_WORKER_NODE = UidWorkerNode.UID_WORKER_NODE;
}
