/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao;


import com.kairlec.koj.dao.tables.Competition;
import com.kairlec.koj.dao.tables.Contestants;
import com.kairlec.koj.dao.tables.Problem;
import com.kairlec.koj.dao.tables.ProblemBelongCompetition;
import com.kairlec.koj.dao.tables.ProblemConfig;
import com.kairlec.koj.dao.tables.ProblemRun;
import com.kairlec.koj.dao.tables.ProblemTag;
import com.kairlec.koj.dao.tables.Submit;
import com.kairlec.koj.dao.tables.SubmitExtend;
import com.kairlec.koj.dao.tables.TagBelongProblem;
import com.kairlec.koj.dao.tables.UidWorkerNode;
import com.kairlec.koj.dao.tables.User;


/**
 * Convenience access to all tables in koj.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 比赛表
     */
    public static final Competition COMPETITION = Competition.COMPETITION;

    /**
     * 参赛者关系表
     */
    public static final Contestants CONTESTANTS = Contestants.CONTESTANTS;

    /**
     * 题目表
     */
    public static final Problem PROBLEM = Problem.PROBLEM;

    /**
     * 题目和比赛关系表
     */
    public static final ProblemBelongCompetition PROBLEM_BELONG_COMPETITION = ProblemBelongCompetition.PROBLEM_BELONG_COMPETITION;

    /**
     * 题目语言配置表
     */
    public static final ProblemConfig PROBLEM_CONFIG = ProblemConfig.PROBLEM_CONFIG;

    /**
     * 题目运行内容表(非spj)
     */
    public static final ProblemRun PROBLEM_RUN = ProblemRun.PROBLEM_RUN;

    /**
     * 题目标签表
     */
    public static final ProblemTag PROBLEM_TAG = ProblemTag.PROBLEM_TAG;

    /**
     * 任务表
     */
    public static final Submit SUBMIT = Submit.SUBMIT;

    /**
     * 任务拓展信息表
     */
    public static final SubmitExtend SUBMIT_EXTEND = SubmitExtend.SUBMIT_EXTEND;

    /**
     * 题目标签关系表
     */
    public static final TagBelongProblem TAG_BELONG_PROBLEM = TagBelongProblem.TAG_BELONG_PROBLEM;

    /**
     * DB WorkerID Assigner for UID Generator
     */
    public static final UidWorkerNode UID_WORKER_NODE = UidWorkerNode.UID_WORKER_NODE;

    /**
     * 用户表
     */
    public static final User USER = User.USER;
}
