lock:
  redis:
    reactive:
      expire-after: 60s
      expire-evict-idle: 5s
      reactive-lock-type:
        - REDIS

spring:
  mail:
    default-encoding: UTF-8
  profiles:
    active: config
debug: true

logging:
  level:
    root: DEBUG
    com.kairlec: DEBUG
    com.baidu: ERROR
    pro.chenggang.project.reactive.lock: WARN
    org.asynchttpclient: INFO
    io.lettuce.core: INFO
    io.netty: INFO
    org.apache.pulsar.common.protocol: INFO
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

pulsar:
  consumer:
    default:
      ack-timeout-ms: 900_000 # 15 minutes
