/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 代码表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Code implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        code;
    private final LocalDateTime createTime;

    public Code(Code value) {
        this.id = value.id;
        this.code = value.code;
        this.createTime = value.createTime;
    }

    public Code(
        Long          id,
        String        code,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.code = code;
        this.createTime = createTime;
    }

    /**
     * Getter for <code>koj.code.id</code>. 代码id(和任务id一致)
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.code.code</code>. 代码
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Getter for <code>koj.code.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Code (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
