/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 比赛表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        name;
    private final LocalDateTime startTime;
    private final LocalDateTime endTime;
    private final LocalDateTime createTime;

    public Competition(Competition value) {
        this.id = value.id;
        this.name = value.name;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.createTime = value.createTime;
    }

    public Competition(
        Long          id,
        String        name,
        LocalDateTime startTime,
        LocalDateTime endTime,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.name = name;
        this.startTime = startTime;
        this.endTime = endTime;
        this.createTime = createTime;
    }

    /**
     * Getter for <code>koj.competition.id</code>. 比赛id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.competition.name</code>. 比赛名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>koj.competition.start_time</code>. 比赛开始时间
     */
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Getter for <code>koj.competition.end_time</code>. 比赛结束时间
     */
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Getter for <code>koj.competition.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Competition (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
