/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 参赛者关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contestants implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          userId;
    private final Long          competitionId;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public Contestants(Contestants value) {
        this.userId = value.userId;
        this.competitionId = value.competitionId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Contestants(
        Long          userId,
        Long          competitionId,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.userId = userId;
        this.competitionId = competitionId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.contestants.user_id</code>. 用户id
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>koj.contestants.competition_id</code>. 比赛id
     */
    public Long getCompetitionId() {
        return this.competitionId;
    }

    /**
     * Getter for <code>koj.contestants.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.contestants.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contestants (");

        sb.append(userId);
        sb.append(", ").append(competitionId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
