/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 题目标签表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProblemTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        name;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public ProblemTag(ProblemTag value) {
        this.id = value.id;
        this.name = value.name;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public ProblemTag(
        Long          id,
        String        name,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.problem_tag.id</code>. 标签id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.problem_tag.name</code>. 标签名
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>koj.problem_tag.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.problem_tag.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProblemTag (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
