/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 题目运行内容表(非spj)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProblemRun implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        stdin;
    private final String        ansout;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public ProblemRun(ProblemRun value) {
        this.id = value.id;
        this.stdin = value.stdin;
        this.ansout = value.ansout;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public ProblemRun(
        Long          id,
        String        stdin,
        String        ansout,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.stdin = stdin;
        this.ansout = ansout;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.problem_run.id</code>. 题目id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.problem_run.stdin</code>. 输入
     */
    public String getStdin() {
        return this.stdin;
    }

    /**
     * Getter for <code>koj.problem_run.ansout</code>. 答案输出(用于)
     */
    public String getAnsout() {
        return this.ansout;
    }

    /**
     * Getter for <code>koj.problem_run.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.problem_run.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProblemRun (");

        sb.append(id);
        sb.append(", ").append(stdin);
        sb.append(", ").append(ansout);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
