/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 题目表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Problem implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        name;
    private final String        content;
    private final Boolean       spj;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public Problem(Problem value) {
        this.id = value.id;
        this.name = value.name;
        this.content = value.content;
        this.spj = value.spj;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Problem(
        Long          id,
        String        name,
        String        content,
        Boolean       spj,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.name = name;
        this.content = content;
        this.spj = spj;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.problem.id</code>. 题目id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.problem.name</code>. 题目名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>koj.problem.content</code>. 题目内容(压缩过)
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>koj.problem.spj</code>. 是否为spj
     */
    public Boolean getSpj() {
        return this.spj;
    }

    /**
     * Getter for <code>koj.problem.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.problem.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Problem (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(content);
        sb.append(", ").append(spj);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
