/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 任务表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submit implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final Byte          state;
    private final Long          problemId;
    private final String        languageId;
    private final Integer       castMemory;
    private final Integer       castTime;
    private final Long          belongCompetitionId;
    private final Long          belongUserId;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public Submit(Submit value) {
        this.id = value.id;
        this.state = value.state;
        this.problemId = value.problemId;
        this.languageId = value.languageId;
        this.castMemory = value.castMemory;
        this.castTime = value.castTime;
        this.belongCompetitionId = value.belongCompetitionId;
        this.belongUserId = value.belongUserId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Submit(
        Long          id,
        Byte          state,
        Long          problemId,
        String        languageId,
        Integer       castMemory,
        Integer       castTime,
        Long          belongCompetitionId,
        Long          belongUserId,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.state = state;
        this.problemId = problemId;
        this.languageId = languageId;
        this.castMemory = castMemory;
        this.castTime = castTime;
        this.belongCompetitionId = belongCompetitionId;
        this.belongUserId = belongUserId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.submit.id</code>. 任务id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.submit.state</code>. 任务状态
     */
    public Byte getState() {
        return this.state;
    }

    /**
     * Getter for <code>koj.submit.problem_id</code>. 题目id
     */
    public Long getProblemId() {
        return this.problemId;
    }

    /**
     * Getter for <code>koj.submit.language_id</code>. 语言id
     */
    public String getLanguageId() {
        return this.languageId;
    }

    /**
     * Getter for <code>koj.submit.cast_memory</code>. 任务内存
     */
    public Integer getCastMemory() {
        return this.castMemory;
    }

    /**
     * Getter for <code>koj.submit.cast_time</code>. 耗时
     */
    public Integer getCastTime() {
        return this.castTime;
    }

    /**
     * Getter for <code>koj.submit.belong_competition_id</code>. 所属比赛id
     */
    public Long getBelongCompetitionId() {
        return this.belongCompetitionId;
    }

    /**
     * Getter for <code>koj.submit.belong_user_id</code>. 所属用户id
     */
    public Long getBelongUserId() {
        return this.belongUserId;
    }

    /**
     * Getter for <code>koj.submit.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.submit.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Submit (");

        sb.append(id);
        sb.append(", ").append(state);
        sb.append(", ").append(problemId);
        sb.append(", ").append(languageId);
        sb.append(", ").append(castMemory);
        sb.append(", ").append(castTime);
        sb.append(", ").append(belongCompetitionId);
        sb.append(", ").append(belongUserId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
