/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 任务拓展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmitExtend implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        code;
    private final String        stdout;
    private final String        stderr;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public SubmitExtend(SubmitExtend value) {
        this.id = value.id;
        this.code = value.code;
        this.stdout = value.stdout;
        this.stderr = value.stderr;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public SubmitExtend(
        Long          id,
        String        code,
        String        stdout,
        String        stderr,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.code = code;
        this.stdout = stdout;
        this.stderr = stderr;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.submit_extend.id</code>. 任务id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.submit_extend.code</code>. 代码
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Getter for <code>koj.submit_extend.stdout</code>. 标准输出
     */
    public String getStdout() {
        return this.stdout;
    }

    /**
     * Getter for <code>koj.submit_extend.stderr</code>. 标准错误
     */
    public String getStderr() {
        return this.stderr;
    }

    /**
     * Getter for <code>koj.submit_extend.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.submit_extend.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SubmitExtend (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(stdout);
        sb.append(", ").append(stderr);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
