/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 任务表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final Long          type;
    private final Byte          state;
    private final Integer       castMemory;
    private final Integer       castTime;
    private final Long          belongCompetitionId;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;

    public Task(Task value) {
        this.id = value.id;
        this.type = value.type;
        this.state = value.state;
        this.castMemory = value.castMemory;
        this.castTime = value.castTime;
        this.belongCompetitionId = value.belongCompetitionId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Task(
        Long          id,
        Long          type,
        Byte          state,
        Integer       castMemory,
        Integer       castTime,
        Long          belongCompetitionId,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.type = type;
        this.state = state;
        this.castMemory = castMemory;
        this.castTime = castTime;
        this.belongCompetitionId = belongCompetitionId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>koj.task.id</code>. 任务id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.task.type</code>. 任务类型
     */
    public Long getType() {
        return this.type;
    }

    /**
     * Getter for <code>koj.task.state</code>. 任务状态
     */
    public Byte getState() {
        return this.state;
    }

    /**
     * Getter for <code>koj.task.cast_memory</code>. 任务内存
     */
    public Integer getCastMemory() {
        return this.castMemory;
    }

    /**
     * Getter for <code>koj.task.cast_time</code>. 耗时
     */
    public Integer getCastTime() {
        return this.castTime;
    }

    /**
     * Getter for <code>koj.task.belong_competition_id</code>. 所属比赛id
     */
    public Long getBelongCompetitionId() {
        return this.belongCompetitionId;
    }

    /**
     * Getter for <code>koj.task.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.task.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(state);
        sb.append(", ").append(castMemory);
        sb.append(", ").append(castTime);
        sb.append(", ").append(belongCompetitionId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
