/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * DB WorkerID Assigner for UID Generator
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UidWorkerNode implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        hostName;
    private final String        port;
    private final Integer       type;
    private final LocalDate     launchDate;
    private final LocalDateTime updateTime;
    private final LocalDateTime createTime;

    public UidWorkerNode(UidWorkerNode value) {
        this.id = value.id;
        this.hostName = value.hostName;
        this.port = value.port;
        this.type = value.type;
        this.launchDate = value.launchDate;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public UidWorkerNode(
        Long          id,
        String        hostName,
        String        port,
        Integer       type,
        LocalDate     launchDate,
        LocalDateTime updateTime,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.hostName = hostName;
        this.port = port;
        this.type = type;
        this.launchDate = launchDate;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * Getter for <code>koj.uid_worker_node.id</code>. auto increment id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.uid_worker_node.host_name</code>. host name
     */
    public String getHostName() {
        return this.hostName;
    }

    /**
     * Getter for <code>koj.uid_worker_node.port</code>. port
     */
    public String getPort() {
        return this.port;
    }

    /**
     * Getter for <code>koj.uid_worker_node.type</code>. node type: ACTUAL or
     * CONTAINER
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Getter for <code>koj.uid_worker_node.launch_date</code>. launch date
     */
    public LocalDate getLaunchDate() {
        return this.launchDate;
    }

    /**
     * Getter for <code>koj.uid_worker_node.update_time</code>. modified time
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Getter for <code>koj.uid_worker_node.create_time</code>. created time
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UidWorkerNode (");

        sb.append(id);
        sb.append(", ").append(hostName);
        sb.append(", ").append(port);
        sb.append(", ").append(type);
        sb.append(", ").append(launchDate);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
