/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final String        username;
    private final String        password;
    private final String        email;
    private final Byte          type;
    private final LocalDateTime createTime;
    private final LocalDateTime updateTime;
    private final Boolean       blocked;

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.email = value.email;
        this.type = value.type;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.blocked = value.blocked;
    }

    public User(
        Long          id,
        String        username,
        String        password,
        String        email,
        Byte          type,
        LocalDateTime createTime,
        LocalDateTime updateTime,
        Boolean       blocked
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.type = type;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.blocked = blocked;
    }

    /**
     * Getter for <code>koj.user.id</code>. 用户id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>koj.user.username</code>. 用户名
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Getter for <code>koj.user.password</code>. 密码(脱敏后)
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>koj.user.email</code>. 用户邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>koj.user.type</code>. 用户类型: 0-普通用户, 1-管理员
     */
    public Byte getType() {
        return this.type;
    }

    /**
     * Getter for <code>koj.user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Getter for <code>koj.user.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Getter for <code>koj.user.blocked</code>. 是否被禁用: 0-未禁用, 1-禁用
     */
    public Boolean getBlocked() {
        return this.blocked;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(type);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(blocked);

        sb.append(")");
        return sb.toString();
    }
}
