/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.records;


import com.kairlec.koj.dao.tables.ProblemConfig;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 题目语言配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProblemConfigRecord extends UpdatableRecordImpl<ProblemConfigRecord> implements Record6<Long, Long, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>koj.problem_config.problem_id</code>. 题目id
     */
    public ProblemConfigRecord setProblemId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.problem_id</code>. 题目id
     */
    public Long getProblemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>koj.problem_config.language_id</code>. 语言id
     */
    public ProblemConfigRecord setLanguageId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.language_id</code>. 语言id
     */
    public Long getLanguageId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>koj.problem_config.memory</code>. 内存限制
     */
    public ProblemConfigRecord setMemory(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.memory</code>. 内存限制
     */
    public Integer getMemory() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>koj.problem_config.time</code>. 时间限制
     */
    public ProblemConfigRecord setTime(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.time</code>. 时间限制
     */
    public Integer getTime() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>koj.problem_config.create_time</code>. 创建时间
     */
    public ProblemConfigRecord setCreateTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>koj.problem_config.update_time</code>. 更新时间
     */
    public ProblemConfigRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_config.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProblemConfig.PROBLEM_CONFIG.PROBLEM_ID;
    }

    @Override
    public Field<Long> field2() {
        return ProblemConfig.PROBLEM_CONFIG.LANGUAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ProblemConfig.PROBLEM_CONFIG.MEMORY;
    }

    @Override
    public Field<Integer> field4() {
        return ProblemConfig.PROBLEM_CONFIG.TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ProblemConfig.PROBLEM_CONFIG.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ProblemConfig.PROBLEM_CONFIG.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getProblemId();
    }

    @Override
    public Long component2() {
        return getLanguageId();
    }

    @Override
    public Integer component3() {
        return getMemory();
    }

    @Override
    public Integer component4() {
        return getTime();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getProblemId();
    }

    @Override
    public Long value2() {
        return getLanguageId();
    }

    @Override
    public Integer value3() {
        return getMemory();
    }

    @Override
    public Integer value4() {
        return getTime();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public ProblemConfigRecord value1(Long value) {
        setProblemId(value);
        return this;
    }

    @Override
    public ProblemConfigRecord value2(Long value) {
        setLanguageId(value);
        return this;
    }

    @Override
    public ProblemConfigRecord value3(Integer value) {
        setMemory(value);
        return this;
    }

    @Override
    public ProblemConfigRecord value4(Integer value) {
        setTime(value);
        return this;
    }

    @Override
    public ProblemConfigRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ProblemConfigRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ProblemConfigRecord values(Long value1, Long value2, Integer value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProblemConfigRecord
     */
    public ProblemConfigRecord() {
        super(ProblemConfig.PROBLEM_CONFIG);
    }

    /**
     * Create a detached, initialised ProblemConfigRecord
     */
    public ProblemConfigRecord(Long problemId, Long languageId, Integer memory, Integer time, LocalDateTime createTime, LocalDateTime updateTime) {
        super(ProblemConfig.PROBLEM_CONFIG);

        setProblemId(problemId);
        setLanguageId(languageId);
        setMemory(memory);
        setTime(time);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }

    /**
     * Create a detached, initialised ProblemConfigRecord
     */
    public ProblemConfigRecord(com.kairlec.koj.dao.tables.pojos.ProblemConfig value) {
        super(ProblemConfig.PROBLEM_CONFIG);

        if (value != null) {
            setProblemId(value.getProblemId());
            setLanguageId(value.getLanguageId());
            setMemory(value.getMemory());
            setTime(value.getTime());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
        }
    }
}
