/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.records;


import com.kairlec.koj.dao.tables.ProblemTag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 题目标签表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProblemTagRecord extends UpdatableRecordImpl<ProblemTagRecord> implements Record4<Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>koj.problem_tag.id</code>. 标签id
     */
    public ProblemTagRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_tag.id</code>. 标签id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>koj.problem_tag.name</code>. 标签名
     */
    public ProblemTagRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_tag.name</code>. 标签名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>koj.problem_tag.create_time</code>. 创建时间
     */
    public ProblemTagRecord setCreateTime(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_tag.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>koj.problem_tag.update_time</code>. 更新时间
     */
    public ProblemTagRecord setUpdateTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>koj.problem_tag.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProblemTag.PROBLEM_TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return ProblemTag.PROBLEM_TAG.NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ProblemTag.PROBLEM_TAG.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProblemTag.PROBLEM_TAG.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    @Override
    public ProblemTagRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProblemTagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProblemTagRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ProblemTagRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ProblemTagRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProblemTagRecord
     */
    public ProblemTagRecord() {
        super(ProblemTag.PROBLEM_TAG);
    }

    /**
     * Create a detached, initialised ProblemTagRecord
     */
    public ProblemTagRecord(Long id, String name, LocalDateTime createTime, LocalDateTime updateTime) {
        super(ProblemTag.PROBLEM_TAG);

        setId(id);
        setName(name);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
