/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.records;


import com.kairlec.koj.dao.tables.SubmitExtend;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 任务拓展信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubmitExtendRecord extends UpdatableRecordImpl<SubmitExtendRecord> implements Record6<Long, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>koj.submit_extend.id</code>. 任务id
     */
    public SubmitExtendRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.id</code>. 任务id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>koj.submit_extend.code</code>. 代码
     */
    public SubmitExtendRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.code</code>. 代码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>koj.submit_extend.stdout</code>. 标准输出
     */
    public SubmitExtendRecord setStdout(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.stdout</code>. 标准输出
     */
    public String getStdout() {
        return (String) get(2);
    }

    /**
     * Setter for <code>koj.submit_extend.stderr</code>. 标准错误
     */
    public SubmitExtendRecord setStderr(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.stderr</code>. 标准错误
     */
    public String getStderr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>koj.submit_extend.create_time</code>. 创建时间
     */
    public SubmitExtendRecord setCreateTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>koj.submit_extend.update_time</code>. 更新时间
     */
    public SubmitExtendRecord setUpdateTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>koj.submit_extend.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SubmitExtend.SUBMIT_EXTEND.ID;
    }

    @Override
    public Field<String> field2() {
        return SubmitExtend.SUBMIT_EXTEND.CODE;
    }

    @Override
    public Field<String> field3() {
        return SubmitExtend.SUBMIT_EXTEND.STDOUT;
    }

    @Override
    public Field<String> field4() {
        return SubmitExtend.SUBMIT_EXTEND.STDERR;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SubmitExtend.SUBMIT_EXTEND.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SubmitExtend.SUBMIT_EXTEND.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getStdout();
    }

    @Override
    public String component4() {
        return getStderr();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getStdout();
    }

    @Override
    public String value4() {
        return getStderr();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public SubmitExtendRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SubmitExtendRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SubmitExtendRecord value3(String value) {
        setStdout(value);
        return this;
    }

    @Override
    public SubmitExtendRecord value4(String value) {
        setStderr(value);
        return this;
    }

    @Override
    public SubmitExtendRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SubmitExtendRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SubmitExtendRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubmitExtendRecord
     */
    public SubmitExtendRecord() {
        super(SubmitExtend.SUBMIT_EXTEND);
    }

    /**
     * Create a detached, initialised SubmitExtendRecord
     */
    public SubmitExtendRecord(Long id, String code, String stdout, String stderr, LocalDateTime createTime, LocalDateTime updateTime) {
        super(SubmitExtend.SUBMIT_EXTEND);

        setId(id);
        setCode(code);
        setStdout(stdout);
        setStderr(stderr);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }

    /**
     * Create a detached, initialised SubmitExtendRecord
     */
    public SubmitExtendRecord(com.kairlec.koj.dao.tables.pojos.SubmitExtend value) {
        super(SubmitExtend.SUBMIT_EXTEND);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setStdout(value.getStdout());
            setStderr(value.getStderr());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
        }
    }
}
