/*
 * This file is generated by jOOQ.
 */
package com.kairlec.koj.dao.tables.records;


import com.kairlec.koj.dao.tables.TagBelongProblem;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 题目标签关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagBelongProblemRecord extends UpdatableRecordImpl<TagBelongProblemRecord> implements Record4<Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>koj.tag_belong_problem.problem_id</code>. 题目id
     */
    public TagBelongProblemRecord setProblemId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>koj.tag_belong_problem.problem_id</code>. 题目id
     */
    public Long getProblemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>koj.tag_belong_problem.tag_id</code>. 标签id
     */
    public TagBelongProblemRecord setTagId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>koj.tag_belong_problem.tag_id</code>. 标签id
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>koj.tag_belong_problem.create_time</code>. 创建时间
     */
    public TagBelongProblemRecord setCreateTime(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>koj.tag_belong_problem.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>koj.tag_belong_problem.update_time</code>. 更新时间
     */
    public TagBelongProblemRecord setUpdateTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>koj.tag_belong_problem.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TagBelongProblem.TAG_BELONG_PROBLEM.PROBLEM_ID;
    }

    @Override
    public Field<Long> field2() {
        return TagBelongProblem.TAG_BELONG_PROBLEM.TAG_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TagBelongProblem.TAG_BELONG_PROBLEM.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TagBelongProblem.TAG_BELONG_PROBLEM.UPDATE_TIME;
    }

    @Override
    public Long component1() {
        return getProblemId();
    }

    @Override
    public Long component2() {
        return getTagId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    @Override
    public Long value1() {
        return getProblemId();
    }

    @Override
    public Long value2() {
        return getTagId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    @Override
    public TagBelongProblemRecord value1(Long value) {
        setProblemId(value);
        return this;
    }

    @Override
    public TagBelongProblemRecord value2(Long value) {
        setTagId(value);
        return this;
    }

    @Override
    public TagBelongProblemRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TagBelongProblemRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TagBelongProblemRecord values(Long value1, Long value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagBelongProblemRecord
     */
    public TagBelongProblemRecord() {
        super(TagBelongProblem.TAG_BELONG_PROBLEM);
    }

    /**
     * Create a detached, initialised TagBelongProblemRecord
     */
    public TagBelongProblemRecord(Long problemId, Long tagId, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TagBelongProblem.TAG_BELONG_PROBLEM);

        setProblemId(problemId);
        setTagId(tagId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }
}
