version: '3.9'

services:
  koj-kt:
    image: kairlec/koj-support:jvm8
    container_name: koj
    environment:
      - KEEP_STDIN=false
      - KEEP_STDOUT=false
      - MAX_CPU_TIME=-1
      - MAX_REAL_TIME=-1
      - MAX_MEMORY=-1
      - MAX_STACK=-1
      - MAX_PROCESS_NUMBER=-1
      - MAX_OUTPUT_SIZE=-1
      - MEMORY_LIMIT_CHECK_ONLY=1
      - EXE_PATH=/usr/sbin/java
      - ARGS=-Djava.security.manager;-Djava.security.policy=/etc/policy/java.policy;-Dfile.encoding=UTF-8;MainKt;
      - ADDON_PATH=
      - ENV=ONLINE_JUDGE=ONLINE_JUDGE
    volumes:
      - /tmp/koj-123456-97765254011212643:/tmp/koj
    tty: true
    stdin_open: true
    command: sh
